version: '3.8'
services:
  library:
    image: postgres:18-alpine
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=library
    restart: on-failure
    volumes:
      - library-data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
volumes:
  library-data:
  minio-data: